services:
  express_api:
    image: ghcr.io/nathansegers/temi/express-api:latest
    ports:
      - 3001:3001
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=development